### ISSUE TITLE
是mavlink2.0的吗

### ISSUE THREAD

**Issue by Dreamskya** [108368012/MAVLink_Android_APP#1]

**Comment by Krissuuu** [comment]
MAVLink 1.0

**Comment by Dreamskya** [comment]
如何集成2.0？您知道吗

**Comment by Krissuuu** [comment]
你可以參考 https://github.com/dronefleet/mavlink 我主要是用他的 library 再參考我的程式，我想應該大同小異

**Comment by Dreamskya** [comment]
您好，方便加个联系方式吗？我也是做无人机这块的。QQ 694862446 想跟你交流下

**Comment by Krissuuu** [comment]
有其他通訊方式嗎? 我沒有在用QQ，sorry，不然你可以留言在這邊我看到就會回覆~

**Comment by Dreamskya** [comment]
哈哈，微信，也可以，也是那个号码  694862446   mavlink 2.0知道怎么用了。想跟你交个朋友，互相学习下

**Comment by Dreamskya** [comment]
是不是飞控板子固件也要mavlink 2.0  ，Android程序切换mavlink 2.0 接口，才能使用上？
我看飞控板子固件是mavlink 1.0 的，Android程序切换mavlink 2.0接口，不能正常。这块你清楚吗？

**Comment by Krissuuu** [comment]
mavlink 2.0這部分不太清楚，專案主要用mavlink 1.0!
